package MPS.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_OperationBinaire_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_OperationBinaire_InferenceRule() {
  }
  public void applyRule(final SNode operationBinaire, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = operationBinaire;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:2b8060cb-a9d0-4eff-bb46-cb6c8f2131b7(MPS.typesystem)", "325614642035206916", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:2b8060cb-a9d0-4eff-bb46-cb6c8f2131b7(MPS.typesystem)", "325614642035206258", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(operationBinaire, LINKS.gauche$$8R4), "r:2b8060cb-a9d0-4eff-bb46-cb6c8f2131b7(MPS.typesystem)", "325614642035206932", true), _info_12389875345);
    }
    if (!(typeCheckingContext.isSingleTypeComputation())) {
      {
        SNode _nodeToCheck_1029348928467 = operationBinaire;
        EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:2b8060cb-a9d0-4eff-bb46-cb6c8f2131b7(MPS.typesystem)", "325614642035208912", 0, null);
        typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(operationBinaire, LINKS.gauche$$8R4), "r:2b8060cb-a9d0-4eff-bb46-cb6c8f2131b7(MPS.typesystem)", "325614642035208197", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(operationBinaire, LINKS.droite$$9l6), "r:2b8060cb-a9d0-4eff-bb46-cb6c8f2131b7(MPS.typesystem)", "325614642035208941", true), true, _info_12389875345);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.OperationBinaire$dM;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink gauche$$8R4 = MetaAdapterFactory.getContainmentLink(0x193ba053c75c4c68L, 0x86ae9cea4678ede8L, 0x2d7e4af03a7fe047L, 0x2d7e4af03a837e92L, "gauche");
    /*package*/ static final SContainmentLink droite$$9l6 = MetaAdapterFactory.getContainmentLink(0x193ba053c75c4c68L, 0x86ae9cea4678ede8L, 0x2d7e4af03a7fe047L, 0x2d7e4af03a837e94L, "droite");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept OperationBinaire$dM = MetaAdapterFactory.getConcept(0x193ba053c75c4c68L, 0x86ae9cea4678ede8L, 0x2d7e4af03a7fe047L, "MPS.structure.OperationBinaire");
  }
}
